### ISSUE TITLE
[Suggestions] Identify orphaned offers & display NFTokenIDs

### ISSUE THREAD

**Issue by effofexx** [lathanbritz/NFT-Flush#1]
First off - well done with this xApp! Super useful.

Hopefully you're open to feedback? If so, I have a couple suggestions:

<br/>

**1) Identify orphaned NFTokenOffer objects within the list of open offers for the account**

I think this would be useful because it's the primary reason why I like to use the NFT Flush xApp, personally. Whenever I sell an NFT, I create offers on multiple marketplaces and then when it's sold, I manually cancel the remaining orphaned offer(s).
      
Sometimes it's easy to identify which ones are orphaned because the image is displayed, but sometimes the images aren't displayed. In that case, I end up needing to do some digging to identify which offers have become orphaned.

<br/>
<br/>

Speaking of the images not always displaying, that brings me to the next suggestion:

**2) When the image is not able to display under the "NFT" column, I think it would make more sense to show the NFTokenID instead of its associated NFTokenOffer Object ID**

One time I was trying to cancel an offer for an NFT I still owned but the images weren't displaying in the xApp, so I had to look at the IDs in the "NFT" column instead. I thought I was losing my mind for a couple minutes trying to figure which of NFTs had the ID I was seeing in the xApp... until I realized it was referring to the offer object lol. So yeah, given the column name is "NFT" I think it makes more sense to list the NFTokenID there instead.

I think this second suggestion would not be needed if the images were always able to be displayed, but sometimes they just don't and I'm not sure why. It appears to be random tbh, and isn't dependent on the particular NFT (sometimes the image will display for a NFT, and sometimes it won't display for the same NFT).

<br/>
<br/>

Anyway... these are just some thoughts I had. Keep up the great work, man! 🍻

**Comment by shortthefomo** [comment]
Thank you kindly,

1) yup https://twitter.com/ShortTheFOMO/status/1603770470448345089?s=20&t=4HLAoGkBwXaFU2LlQ6pLbA will get done.

2) im also confused as to what ID to show... issue is you can have multiple offers agains same NFT nothing stopping that. does not quite make sense to show same ID x2 for those two... but open to explore better option here over time.

**Comment by shortthefomo** [comment]
Orphans are now open for testing.

https://twitter.com/ShortTheFOMO/status/1604140770914467841?s=20&t=Y6k9AvlAYSKrcWgr7t6fYA

**Comment by effofexx** [comment]
Nice! I'll check it out.

About the IDs - yeah that is a bit tricky given that there's only so much real estate available in an xApp. I think either way would work tbh. If the NFToken IDs are shown, that's kinda the same as when the images display. On the other hand, what you're showing really are the offers, so it makes sense to show the offer IDs. Either way, users should at least have some idea of what offers they've made anyway, so it's all good!
